FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

ENV PYTHONUNBUFFERED 1

# ARG UID
# ARG GID
# ARG USERNAME=developer


# RUN groupadd -g ${GID} ${USERNAME} && \
#     useradd -m -u ${UID} -g ${GID} -s /usr/bin/fish ${USERNAME} && \
#     usermod -aG root ${USERNAME} && \
#     usermod -aG sudo ${USERNAME} && \
#     echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USERNAME}

# USER ${USERNAME}

# [Optional] If your requirements rarely change, uncomment this section to add them to the image.
# COPY requirements.txt /tmp/pip-tmp/
# RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
#    && rm -rf /tmp/pip-tmp

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>



