version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    env_file: ./.env
    volumes:
      - ../..:/workspaces:cached
      - ${HOME}/.ssh:/mnt/config/.ssh:cached
      - ${HOME}/.gitconfig:/mnt/config/.gitconfig:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongodb/mongodb-atlas-local
    restart: unless-stopped
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

    # image: mongodb/atlas:latest
    # command: |
    #   /bin/bash -c "atlas deployments setup --type local --port 27017 --bindIpAll --mdbVersion 6.0 --username root --password root --force && tail -f /dev/null"
    # environment:
    # - ATLAS_STORAGE_ENGINE=wiredTiger
    # - ATLAS_REPL_SET_NAME=atlas
    # - ATLAS_SERVER_KEY=/data/mongodb/certs/server.pem
    # - ATLAS_CLIENT_CERT=/data/mongodb/certs/client.pem
    # - ATLAS_REPLICA_SET_MODE=primary
    volumes:
      - mongodb-atlas-data:/data/mongodb

    # ports:
    # - "27017:27017"

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-atlas-data:
